image: ubuntu:18.04

stages:
  - validate

before_script:
  - apt update
  - apt install -y software-properties-common
  - add-apt-repository -y universe
  - apt install -y appstream-util desktop-file-utils shellcheck jsonlint

validate_appdata:
  stage: validate
  script:
    - appstream-util validate-relax data/application.appdata.xml

validate_desktop:
  stage: validate
  script:
    - desktop-file-validate data/application.desktop

validate_launcher:
  stage: validate
  script:
    - shellcheck data/launch.sh

validate_manifest:
  stage: validate
  script:
    - jsonlint-php com.riotgames.League_of_Legends.json
